name: Daily BTC/ETH Report

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00，也就是台灣時間早上 08:00
  workflow_dispatch:      # 支援手動觸發

jobs:
  call-report:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger /report endpoint
        run: |
          curl -s https://btc-eth-reporter.onrender.com/report
